name: Build and deploy to Azure Function App #optional, add app name, dotnet version, etc

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # set this to the path to your web app project, defaults to the repository root
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  # set this to the dotnet version to use
  DOTNET_VERSION: '6.0.x' 
  # Put your app name here
  AZURE_FA_NAME: 'your-function-app-name-here' 
  # staging by default but you could change to Production if you are not creating a slot 
  AZURE_FA_SLOT: 'staging' 
  #Make sure you create a secret with the publish profile named exactly as AZURE_PUBLISH_PROFILE
  AZURE_PUBLISH_PROFILE_SECRET: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{ env.AZURE_FA_NAME }}'
          slot-name: '${{ env.AZURE_FA_SLOT }}'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE_SECRET }}